n_runs: 1
valid_size: 0.15
test_size: 0.15
pos_weight: 1.5
fw_batch_size: 128

train:
  bw_batch_size: 128
  lr: 1e-3
  weight_decay: 1e-4
  epochs: 200
  patience: 8
  aggregation: mean
  load_path:
  save_path:
  
test_aggregation: mean