model:
  arch: vit_base
  num_register_tokens: 4
  patch_size: 14
  drop_path_rate: 0.0
  ffn_layer: mlp
  weights:  /lustre/mammo-filter/weights/dinov2_vitb14_reg4_pretrain.pth  #/home/nikola.jovisic.ivi/nj/mama-encoder/mama_embed_pretrained_40k_steps_last_dinov2_vit_ckpt.pth
  layerscale: 1.0e-05
  block_chunks: 0
  qkv_bias: true
  proj_bias: true
  ffn_bias: true  
  interpolate_antialias: false
  interpolate_offset: 0.1
  drop_path_uniform: true
  img_size: 518
  
embeddings_root: /home/nikola.jovisic.ivi/nj/lustre_mock/

batch_size: 8
img_loader_workers: 16
tile_loader_workers: 16

run_name: lorem-ipsum
run_description: "Lorem ipsum."